#' Calculate median age at first reproduction
#'
#' Returns a dplyr::tbl_df.
#'
#' @param b Name of the tbl_df containing biography data generated by the function read_bio_table.
#' @export
#' @examples
#' a <- median_age_first_rep(lh)
median_age_first_rep <- function(b){

  # Find all animals that are first born offspring
  # Since there are currently errors in the first-born column,
  # choose the first offspring for each mother that is called her first-born
  fb <- b %>%
    dplyr::filter(First.Born == "Y") %>%
    dplyr::group_by(Study.Id, Mom.Id) %>%
    dplyr::arrange(Birth.Date) %>%
    dplyr::summarise(Animal.Id = dplyr::first(Animal.Id),
              Birth.Date = dplyr::first(Birth.Date),
              Sex = dplyr::first(Sex),
              First.Born = dplyr::first(First.Born)) %>%
    dplyr::select(Study.Id, Animal.Id, Birth.Date, Mom.Id, First.Born, Sex)

  # Create a temporary data frame of mothers of these animals with their birth dates
  # Note that cases where Mom.Id doesn't match exactly with Animal.Id are dropped silently
  # Use find_mom_errors() function to find these cases!
  mothers <- suppressWarnings(dplyr::semi_join(b, fb,
                                               by = c("Study.Id" = "Study.Id",
                                                      "Animal.Id" = "Mom.Id")))
  mothers <- mothers %>%
    dplyr::select(Study.Id, Animal.Id, Birth.Date) %>%
    dplyr::rename(Mother.Birth.Date = Birth.Date)

  # For first-born animals in fb, get the mother's birth date using inner join
  temp <- suppressWarnings(dplyr::inner_join(fb, mothers, by = c("Study.Id" = "Study.Id",
                                                                 "Mom.Id" = "Animal.Id")))

  # Calculate mother's age when the first offspring was born
  med_age <- temp %>%
    dplyr::mutate(age_days = Birth.Date - Mother.Birth.Date,
                  age_years = lubridate::interval(Mother.Birth.Date,
                                                  Birth.Date) / lubridate::eyears(1)) %>%
    dplyr::group_by(Study.Id) %>%
    dplyr::summarise(median_age_days = median(age_days),
                     median_age_years = median(age_years),
                     n_first_births = n())

  return(med_age)
}


#' Calculate age-specific fertility
#'
#' Returns a dplyr::tbl_df.
#' Based on Bill Morris' methods for calculating vital rates, available on the Wiki.
#'
#' @param b Name of the tbl_df containing biography data generated by the function read_bio_table.
#' @param f Name of the tbl_df containing fertility data generated by the function read_fert_table.
#' @export
#' @examples
#' asf <- age_specific_fertility(lh, fert)
age_specific_fertility <- function(b, f){

  f$Animal.Id <- as.character(f$Animal.Id)
  b$Animal.Id <- as.character(b$Animal.Id)

  # For each female in f (fertility), find her birth date
  # Easily done with an inner join of the two tables
  # Joined on Study.Id and Animal.Id (because some duplication of Animal.Id)
  temp <- dplyr::inner_join(b, f, by = c("Study.Id" = "Study.Id",
                                         "Animal.Id" = "Animal.Id"))

  # Create columns for first and last birthday, and fill with dummy dates
  temp <- dplyr::mutate(temp, FirstBirthday = lubridate::ymd("1900-01-01"),
                 LastBirthday = lubridate::ymd("1900-01-01"))

  # Find the end of each study
  study_end <- b %>%
    dplyr::group_by(Study.Id) %>%
    dplyr::summarise(Study.End = max(Depart.Date))

  # Use another inner join to put the end of study date in the working data frame
  temp <- suppressMessages(dplyr::inner_join(temp, study_end))

  # Create blank list to hold output
  asf <- list()

  # Loop through all entries in working data frame
  for(i in 1:nrow(temp)){

    # Store these values temporarily for future use in matching
    s <- temp[i, ]$Study.Id
    m <- temp[i, ]$Animal.Id

    actual_bd <- temp[i, ]$Birth.Date

    # For now, set end birthday to the birthday on the year that the study ends
    end_bd <- lubridate::ymd(paste(lubridate::year(temp[i, ]$Study.End),
                                    lubridate::month(temp[i, ]$Birth.Date),
                                    lubridate::day(temp[i, ]$Birth.Date),
                                    sep = "-"))

    # If the date of end birthday is before the date of study end,
    # add one year to the end birthday
    if(temp[i, ]$Study.End > end_bd){
      end_bd <- end_bd + lubridate::years(1)
    }

    # Compute dates of the current female's birthdays from year of birth to
    # end birthday determined above
    bd <- seq(actual_bd, end_bd, "1 year")

    # The "FirstBirthday" to be used for fertility analysis is the latest
    # birthday before or on the first date of fertility observation
    first_bd <- max(bd[bd <= temp[i, ]$Start.Date])

    # The "LastBirthday" to be used for fertility analysis is the earliest
    # birthday on or after the last date of fertility observation
    last_bd <- min(bd[bd >= temp[i, ]$Stop.Date])

    # Recalculate the birthday sequence using first and last birthdays
    bd <- seq(first_bd, last_bd, "1 year")

    # Temporary data frame to hold the fertility data for the current female
    # Has one record for each one-year interval between the female's birthdays
    asf_i <- data.frame(Study.Id = temp[i, ]$Study.Id,
                        Animal.Id = temp[i, ]$Animal.Id,
                        Birth.Date = temp[i, ]$Birth.Date,
                        Start.Date = temp[i, ]$Start.Date,
                        Stop.Date = temp[i, ]$Stop.Date,
                        Last.BD = bd[1:(length(bd) - 1)],
                        Next.BD = bd[2:length(bd)],
                        Weight = NA,
                        Num.Offspring = NA)

    # Calculate weight of first year based on fraction of year actually observed
    if(asf_i[1, ]$Last.BD < asf_i[1, ]$Start.Date){
      asf_i[1, ]$Weight <- (asf_i[1, ]$Next.BD - asf_i[1, ]$Start.Date) / lubridate::eyears(1)
    }

    # Calcualte weight of last year based on fraction of year actually observed
    k <- nrow(asf_i)
    if(asf_i[k, ]$Next.BD > asf_i[k, ]$Stop.Date){
      asf_i[k, ]$Weight <- (asf_i[k, ]$Stop.Date - asf_i[k, ]$Last.BD) / lubridate::eyears(1)
    }

    # Set all other weights to 1 because fertility was observed for complete year
    if(nrow(asf_i[is.na(asf_i$Weight), ]) > 0){
      asf_i[is.na(asf_i$Weight), ]$Weight <- 1
    }

    # Calculate discrete age class (i.e., age in years)
    asf_i$Discrete.Age.Class <- lubridate::year(asf_i$Last.BD) - lubridate::year(asf_i$Birth.Date)

    # Loop over current female's birthdays and add up number of individuals born
    # to that female in that year
    for(j in 1:nrow(asf_i)){
      asf_i[j, ]$Num.Offspring <- b %>%
        dplyr::filter(Study.Id == s & Mom.Id == m &
                        Birth.Date >= asf_i[j, ]$Last.BD &
                        Birth.Date < asf_i[j, ]$Next.BD) %>%
        nrow()
    }

    # Add this data frame to the larger list
    asf[[i]] <- asf_i
  }

  # Bind all rows of the list together into one tbl_df
  asf <- suppressWarnings(dplyr::bind_rows(asf))

  # Compute average age-specific per-capita fertility
  asf_summary <- asf %>%
    dplyr::group_by(Study.Id, Discrete.Age.Class) %>%
    dplyr::summarise(f = sum(Num.Offspring * Weight) / sum(Weight),
              n = n())

  return(asf_summary)
}

#' Calculate stage-specific fertility
#' Based on Bill Morris' methods for calculating vital rates, available on the Wiki.
#'
#' Returns a dplyr::tbl_df.
#'
#' @param b Name of the tbl_df containing biography data generated by the function read_bio_table.
#' @param f Name of the tbl_df containing fertility data generated by the function read_fert_table.
#' @param f Logical. Should the fertility be calculated for each year separately?
#' @export
#' @examples
#' ssf <- stage_specific_fertility(lh, fert)
stage_specific_fertility <- function(b, f, annual = TRUE){

  f$Animal.Id <- as.character(f$Animal.Id)
  b$Animal.Id <- as.character(b$Animal.Id)

  # Get subset of animals for which fertility was monitored
  temp <- dplyr::left_join(b, f, by = c("Study.Id" = "Study.Id",
                                        "Animal.Id" = "Animal.Id"))

  # Get life history stage (newborn, juvenile, or adult) of each animal at each
  # pseudocensus date during the study
  ps_ages <- pseudocensus_ages(temp)

  # Join to fertility data to get start and stop dates
  ps_ages <- dplyr::inner_join(ps_ages, f, by = c("Study.Id" = "Study.Id",
                                                  "Animal.Id" = "Animal.Id"))

  ps_ages$Weight <- NA
  ps_ages$Num.Offspring <- NA

  # Remove years for which census_end < Start.Date or census_date > End.Date
  ps_ages <- ps_ages %>%
    dplyr:: mutate(census_end = census_date + lubridate::years(1)) %>%
    dplyr::filter(census_end >= Start.Date & census_date <= Stop.Date)

  # Calculate weight as the proportion of the psuedocensus year for which
  # the female's fertility was observed
  # Takes about 2 minutes to run
  for (i in 1:nrow(ps_ages)){

    # Store these values temporarily for future use in matching
    s <- as.character(ps_ages[i, ]$Study.Id)
    m <- as.character(ps_ages[i, ]$Animal.Id)

    # If start date and end date fully encompass census year, weight is 1
    if(ps_ages[i, ]$census_date >= ps_ages[i, ]$Start.Date &
       ps_ages[i, ]$census_end <= ps_ages[i, ]$Stop.Date){
      ps_ages[i, ]$Weight <- 1
    }

    # Else if census date before start date, fertility observation is censored
    # Get length between start date and min of {census end, stop date}
    else if(ps_ages[i, ]$census_date < ps_ages[i, ]$Start.Date){
      ps_ages[i, ]$Weight <- (min(c(ps_ages[i, ]$census_end,
                                    ps_ages[i, ]$Stop.Date)) -
                                ps_ages[i, ]$Start.Date) / lubridate::eyears(1)
    }

    # Else if stop date is before next census, fertility observation is censored
    # Get length between max of {census start, start date} and stop date
    else if(ps_ages[i, ]$Stop.Date < ps_ages[i, ]$census_end){
      ps_ages[i, ]$Weight <- (ps_ages[i, ]$Stop.Date -
        (max(c(ps_ages[i, ]$census_date, ps_ages[i, ]$Start.Date)))) / lubridate::eyears(1)
    }

    t1 <- ps_ages[i, ]$census_date
    t2 <- ps_ages[i, ]$census_end

    # Add up the number of individuals born to
    # that female in that census year
    ps_ages[i, ]$Num.Offspring <- b %>%
      dplyr::filter(Study.Id == s & Mom.Id == m & Birth.Date >= t1 & Birth.Date < t2) %>%
      nrow()
  }

  if(annual){
    # Compute annual stage-specific per-capita fertility
    ssf_summary <- ps_ages %>%
      dplyr::mutate(year_of = lubridate::year(census_date)) %>%
      dplyr::group_by(Study.Id, year_of, age_class) %>%
      dplyr::summarise(f = sum(Num.Offspring * Weight) / sum(Weight),
                       n = n())
  }
  else{
    # Compute average stage-specific per-capita fertility for all years
    ssf_summary <- ps_ages %>%
      dplyr::group_by(Study.Id, age_class) %>%
      dplyr::summarise(f = sum(Num.Offspring * Weight) / sum(Weight),
                       n = n())
  }

  return(ssf_summary)
}


#' Calculates the age class of an animal based on its age and the median age at
#' first reproduction for the species.
#'
#' Returns a character string: "newborn", "juvenile", or "adult"
#'
#' @param age_years Age of the animal in years.
#' @param mafr Median age of first reproduction in years for the species.
#' @export
#' @examples
#' age_class <- get_age_class(5.1, 8.78589)
get_age_class <- function(age_years, mafr){

  res <- ifelse(age_years < 0, "newborn",
                ifelse(age_years >= 0 & age_years < mafr, "juvenile", "adult"))

  return(res)
}

#' Create pseudocensus dates and calculate ages of all animals present at each census.
#' This function is used by the stage-specific vital rate functions.
#'
#' Returns a dplyr::tbl_df.
#'
#' @param b Name of the tbl_df containing biography data generated by the function read_bio_table.
#' @export
#' @examples
#' ages <- pseudocensus_ages(lh)
pseudocensus_ages <- function(b){

  # pseudocensus
  census <- b %>%
    dplyr::group_by(Study.Id) %>%
    dplyr::summarise(min_entry = min(Entry.Date)) %>%
    dplyr::mutate(census_start = lubridate::ymd(paste(year(min_entry),
                                                      "01", "01", sep = "-")))

  census_end <- b %>%
    dplyr::group_by(Study.Id) %>%
    dplyr::filter(Depart.Type == "O") %>%
    dplyr::summarise(study_end = max(Depart.Date)) %>%
    dplyr::mutate(census_end = lubridate::ceiling_date(study_end,
                                                       unit = "year") - lubridate::years(1))

  census <- suppressMessages(dplyr::inner_join(census, census_end))

  # Fix two special cases where only one animal recorded in first year(s)
  census[census$Study.Id == "beza", ]$census_start <- lubridate::ymd("1984-01-01")
  census[census$Study.Id == "kakamega", ]$census_start <- lubridate::ymd("1980-01-01")

  census_seq <- function(df) {
    seq(df$census_start, df$census_end, "1 year")
  }

  census_dates <- plyr::dlply(census, .(Study.Id), census_seq)

  mafr <- median_age_first_rep(b)

  # For each census date, calculate the age of each animal present
  age_df <- list()
  for(j in 1:7){
    site <- as.character(census[j, ]$Study.Id)
    site_seq <- census_dates[[site]]
    temp_lh <- b %>%
      dplyr::filter(Study.Id == site)

    temp_mafr <- mafr[mafr$Study.Id == site, ]$median_age_years

    ages <- list()
    for(i in 1:length(site_seq)){
      # For each date, extract subset of animals present
      t <- site_seq[i]

      temp_set <- temp_lh %>%
        dplyr::filter(Entry.Date - lubridate::years(1) <= t & Depart.Date >= t)

      # If present, calculate age and assign to age category; calculate weight if neccesary
      ages[[i]] <- temp_set %>%
        dplyr::mutate(age_days = difftime(t, Birth.Date, units = "days"),
                      age_years = lubridate::interval(Birth.Date, t) / lubridate::eyears(1),
                      census_date = t,
                      discrete_age_class = ceiling(age_years),
                      age_class = get_age_class(age_years, temp_mafr)) %>%
        dplyr::select(census_date, 1:4, age_days, age_years,
                      discrete_age_class, age_class, 13:16)
    }

    #   site_ages <- do.call("rbind", ages)
    site_ages <- dplyr::bind_rows(ages)
    age_df[[j]] <- site_ages
  }

  # age_df <- do.call("rbind", age_df)
  age_df <- dplyr::bind_rows(age_df)

  return(age_df)
}